substrait-io/substrait

.github/actions/dev-tool-python/action.yml
.github/workflows/pr.yml
site/docs/_config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/12)

Set up a new PR workflow for checking that site builds correctly.

---

extensions/aggregate_functions.yaml
extensions/scalar_functions.yaml
extensions/window_functions.yaml

Resolves https://github.com/substrait-io/substrait/issues/14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/15)

Remove exception field from YAML function files

---

binary/expression.proto

This closes #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/18)

Remove old literals that no longer have matching types.

---

.github/workflows/pr.yml
binary/foo.proto

Fixes #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/38)

run protoc for PRs

---

binary/expression.proto
binary/function.proto
binary/relations.proto
binary/selection.proto
binary/type.proto

- Add boolean type and literals
- Add a typed null literal
- Fix map type definition
- Add java option to generate multiple files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/37)

Minor protobuf fixes

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/39)

Add common ignore paths

---

site/docs/community.md

Closes #71.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/72)

Fix Docs link on the community page

---

binary/relations.proto

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/75)

Add SEMI and ANTI Join types

---

site/docs/community.md
site/docs/index.md
site/mkdocs.yml

- Change the slack invite link to be a variable within mkdocs.yml
- Update the link for another 30 days.

Update slack link

---

.github/workflows/pr.yml
extensions/extension_types.yaml
extensions/functions_datetime.yaml
extensions/functions_string.yaml
extensions/type_variations.yaml
extensions/unknown.yaml
text/simple_extensions_schema.yaml

- add schema for extensions
- update existing extensions to validate against schema
- add an example "unknown" extension to illustrate simplified possibilities.
- add github workflow to validate yaml files.

Add Schema for YAML extensions

---

.github/workflows/pr.yml
binary/expression.proto
binary/extensions.proto
binary/function.proto
binary/parameterized_types.proto
binary/plan.proto
binary/relations.proto
binary/selection.proto
binary/type.proto
binary/type_expressions.proto

This PR reformats the protobuf files and adds a check in CI to catch any future
non-conforming formatting

Format protobufs with clang-format and check in CI

---

binary/expression.proto

Give List and Map Literal expressions an element type

---

binary/expression.proto

Deduplicate Switch/If expressions according to the intended use case

---

binary/capabilities.proto
site/docs/serialization/binary_serialization.md

- Add a capabilities proto message and documentation description

Introduce Capabilities message type

---

binary/relations.proto
binary/type.proto

Move NamedStruct out of the Type message

---

binary/relations.proto

Requested by @cpcloud, @winningsix and others.
Closes #92

Support grouping expressions in AggregateRel

---

proto/substrait/relations.proto
site/docs/relations/logical_relations.md

These are necessary to run some of the flattened subqueries.

Add CrossProduct Relation and Single-join type

---

.github/workflows/licence_check.yml
.licenserc.yaml
proto/substrait/algebra.proto
proto/substrait/capabilities.proto
proto/substrait/extensions/extensions.proto
proto/substrait/function.proto
proto/substrait/parameterized_types.proto
proto/substrait/plan.proto
proto/substrait/type.proto
proto/substrait/type_expressions.proto

Add license header to .proto files

---

proto/substrait/algebra.proto
site/docs/relations/physical_relations.md

This work is an update based on discussion on #121 (I was unable to update to push these changes to that branch.)

An updated Exchange rel.

---

site/requirements.txt

See: https://github.com/mkdocs/mkdocs/issues/2799

Upgrade mkdocs so that jinja2 bug doesn't cause a problem.

---

extensions/functions_comparison.yaml

not a functional change, just updating the descriptions to match

fix function description for gt and gte

---

site/requirements.txt

This PR fixes the broken website build. xref: https://github.com/pygments/pygments/issues/2119

docs(website): fix broken build by pinning an older pygments

---

.github/workflows/release.yml

This PR fixes the schedule event

ci: fix schedule

---

LICENSE

Remove extraneous info from License

chore: fix license file bad copy/paste

---

site/docs/spec/_config
site/docs/spec/versioning.md

As discussed during the sync meeting, here's my view of versioning combined with what I think is the current consensus, as a starting point for further discussion. RFC

Document version behavior

---

.releaserc.json

I *think* I updated the semantic release configuration according to what I wrote in #209, but I'm a bit confused about how it all works (as well as @cpcloud's mailing list post concerning it) and I'm not sure how to test it.

Update version behavior

---

extensions/functions_string.yaml

This PR added starts_with, ends_with, contains functions to yaml files.

feat: add functions to yaml

---

site/docs/relations/logical_relations.md

BREAKING CHANGE: the grouping set index column now only exists if there is more
than one grouping set.

docs: better explain aggregate relations

---

extensions/functions_arithmetic.yaml

This PR includes aggregate function `product`.

feat: add product function

---

extensions/functions_arithmetic.yaml
text/simple_extensions_schema.yaml

This PR includes standard_deviation definition.

feat: add standard deviation functions

---

extensions/functions_arithmetic.yaml

This PR includes the addition of variance aggregation operator.

feat: add variance function

---

extensions/functions_datetime.yaml

Update descriptions for gt and gte

refactor: update descriptions for gt and gte

---

extensions/functions_comparison.yaml

This PR adds definitions for is_infinite and is_finite.

feat: add is_finite and is_infinite

---

extensions/functions_comparison.yaml

This PR adds 2 conditional functions:  `if_else` and `nullif`.

feat: add nullif function

---

extensions/functions_string.yaml

Add an option to control case sensitivity to string functions that may need it.
BREAKING CHANGE: added option arguments to existing functions.

feat: add case_sensitivity option to string functions

---

extensions/functions_arithmetic.yaml

This PR adds hyperbolic functions

feat: add hyperbolic functions

---

proto/substrait/algebra.proto

feat: add dwrf file format

---

extensions/functions_comparison.yaml
extensions/functions_rounding.yaml

Clarifying some null handling behavior and adding names to all arguments.

docs: improve descriptions of comparison and rounding functions

---

extensions/functions_arithmetic.yaml

In this PR population variance and standard-deviation is added.
BREAKING CHANGE: signature change of `variance` and `std_dev`

feat: add population option to variance and standard deviation functions

---

extensions/functions_arithmetic.yaml

In this PR `corr` and `mode` aggregation functions are added.

feat: add corr and mode aggregation functions

---

extensions/functions_arithmetic.yaml

This PR includes the `quantile` and `approx_quantile` functions for aggregate functions.

feat: add quantile aggregate function

---

extensions/functions_aggregate_generic.yaml
extensions/functions_arithmetic.yaml

This PR  adds `any_value` aggregate function.

feat: add any_value aggregate function

---

proto/substrait/algebra.proto
site/docs/relations/physical_relations.md

This PR includes hashJoin and mergeJoin physical plan relations according the spec

feat(proto): add physical hashJoin & mergeJoin physical relations

---

extensions/functions_arithmetic_decimal.yaml

update extension yaml files to match type-syntax spec

fix: update extension yaml files to match type-syntax spec

---

site/docs/tutorial/sql_to_substrait.md

docs: remove mention of the options in the tutorial

---

site/docs/tools/_config
site/docs/tools/producer_tools.md
site/docs/tools/substrait_validator.md
site/docs/tools/third_party_tools.md

Add a new page linking to existing tools that support substrait.

docs: add tools page

---

site/docs/tutorial/sql_to_substrait.md

Very minor change: used the wrong reference number here in text.

docs: fix function reference number

---

site/docs/tutorial/final_plan.json
site/docs/tutorial/sql_to_substrait.md

fix wrong references to functions in documentation

docs: fix final_plan func references

---

extensions/functions_datetime.yaml

BREAKING CHANGE: This adds an option to control indexing of components as discussed in #477.

feat: control indexing in temporal extraction

---

buf.gen.yaml

Update buf plugin references in the generation template.

build: update buf plugin references in buf.gen.yaml

---

extensions/functions_arithmetic.yaml

PR to add radians and degrees functions

feat: add radians and degrees functions

---

site/docs/expressions/field_references.md

Fixes the code blocks in field_references.md

docs: fix code blocks in field_references.md

---

extensions/functions_comparison.yaml

PR to add `is distinct from` function

feat: add is distinct from function

---

site/docs/relations/basics.md
site/docs/serialization/_config
site/docs/serialization/basics.md

#612 and #613 highlighted a number of ambiguities in plan interpretation.  I have made an attempt to clarify these based on my interpretation.

feat: clarify the meaning of plans

---

extensions/functions_arithmetic_decimal.yaml

Thank you for submitting a PR!
Before you continue, please ensure that your PR title and description (this message!) follow [conventional commit syntax](1). Substrait uses an automated release process that, among other things, uses PR titles & descriptions to build a changelog, so the syntax and format matter!
The title of the PR should be a valid commit header.
Some examples of proper commit message headers and PR titles:
- `feat: add feature X`
- `fix: X in case of Y`
- `docs: improve documentation for X`
Note the case and grammar conventions.
Furthermore, the description of any PR that includes a breaking change should contain a paragraph that starts with `BREAKING CHANGE: ...`, where `...` explains what changed. The automated release process uses this to determine how it should bump …

feat: add arithmetic function "power" with decimal type

---

extensions/functions_arithmetic.yaml

row_number should start counting rows at 1

feat: specify row_number start (#722)

---

proto/substrait/type.proto

Closes https://github.com/substrait-io/substrait/issues/787.

docs: add comment to NamedSchema about struct nullability

---

site/data/committers.yaml

Add the new committers to the [docs page](https://substrait.io/governance/#substrait-committers).

docs: add new committers

---

site/data/committers.yaml

Adding @yongchul to the committer list.

chore: add new committer
