substrait-io/substrait

site/docs/relations/basics.md, site/docs/types/compound_logical_types.md, site/docs/types/simple_logical_types.md
Mkdocs uses python-markdown which allows inline HTML.  Some of the markdown (e.g. `TIMESTAMP<MILLISECOND>`) was being interpreted as HTML tags (and eventually rendering as `TIMESTAMP`).  The recommendation is to escape as `&lt;` and `&gt;`.  It appears that < and > in code tags is acceptable.
Another choice that might lead to more readable markdown is to just use ( and ) in the few places that < and > are currently used outside of code blocks.
One downside of either of the above approaches is that the simple logical types table is now quite wide (and requires scrolling on my viewport).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/5)
=> Escape < and > with &lt; and &gt;

site/docs/types/compound_logical_types.md
It is not clear if there is actually a lower bound restriction on scale.   It isn't mentioned in the arrow spec, I also couldn't find it in Trino, Iceberg or Spark docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/19)
=> Add Decimal(P, S) to types

binary/expression.proto
This PR gives `fixed_binary` the correct protobuf type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/33)
=> Give fixed_binary the correct protobuf type

site/docs/index.md
Per comment in Slack.  This should help clarify things for people coming from an SQL (but not relational algebra / query engine development) background.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/34)
=> Add a 'substrait vs sql' section to the FAQ portion of the page

site/docs/expressions/embedded_functions.md, site/mkdocs.yml, site/requirements.txt
This adds the [mkdocs-protobuf](https://github.com/rymurr/mkdocs-protobuf) extension to the site and adds one protobuf message to the documetnation.
I have just done one as an example of a few ways we might add protobuf definitions:
1) just simply add with a statement like "this is the binary representation"
2) tabbed view which shows the protobuf IDL for a message, the human readable version and an example.
Before making a lot of changes I thought I would see what everyone else thought.
Fixes #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/36)
=> Use markdown extension to embed protobuf IDL in docs

binary/expression.proto, binary/extensions.proto, binary/function.proto, binary/parameterized_types.proto, binary/plan.proto, binary/type.proto, binary/type_expressions.proto, site/docs/expressions/scalar_functions.md
Proposal for simple type expressions to support type parameterization for output type derivation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/40)
=> Propose update for simple output type expressions.

binary/expression.proto, binary/extensions.proto, binary/function.proto, binary/parameterized_types.proto, binary/plan.proto, binary/relations.proto, binary/selection.proto, binary/type.proto, binary/type_expressions.proto
The default `io.substrait` doesn't follow [C# style guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces).
I've proposed here `Substrait.Protobuf` but something like `SubstraitIo.Plan.Protobuf` would probably work as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/66)
=> Update csharp namespace

binary/relations.proto
The join type enum is in JoinRel but not defined as an actual field in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/68)
=> JoinRel type missing type

binary/expression.proto, site/docs/relations/basics.md
I can't find the term "sort type" in very many sources and when I do it is referring to something else (e.g. Redshift's interleaved vs compound).
On the other hand, "direction" is pretty common:
Iceberg and Spark have "SortOrder" which is a "SortDirection" and a "NullOrder".
Postgres calls it the "sort direction"
Splitting into Sort Order, Sort Direction, and Null Order to mirror Iceberg/Spark would be another option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/substrait-io/substrait/67)
=> Rename sort type as sort direction

binary/plan.proto, binary/relations.proto
This PR adds a `NamedRel` message for use at the root of an expression tree.
In particular, it's useful for being able to store a view without loss of information,
as well as being able to round trip a producer for testing.
=> Add NamedRel

binary/expression.proto, binary/extensions.proto, binary/function.proto, binary/parameterized_types.proto, binary/plan.proto, binary/relations.proto, binary/selection.proto, binary/type.proto, binary/type_expressions.proto, site/docs/expressions/specialized_record_expressions.md, site/docs/relations/logical_relations.md
- Add java package name for all proto files
- Add an explicit CAST expression
- Update the varchar literal to specify it's length
- Move AggregateFunction, AggregationPhase and SortField out of the Expression message (top-level in expression.proto).
- Remove AggregationPhase from aggregate rel since it is specified on the individual aggregation function bindings
- Add support for a filter as part of an aggregation measure (SQL2003)
- Cleanup some markdown linebreaks
- Add ReturnProgram to derivation expression to support SSA return definition (reduce repetition)
=> Minor expression cleanups

proto/substrait/expression.proto
Proposing either the changes in this PR or alternatively changing
`List.values` to `List.elements` so that the `*_type` argument is
consistent with the field name.
=> refactor: change field name for List value type

proto/substrait/relations.proto
This pr adds the Partition Infos in ReadRel.
Closes https://github.com/substrait-io/substrait/issues/101.
=> Add Partition Infos in ReadRel

proto/substrait/extensions/extensions.proto
(instead of using _pointer sometimes)
=> Name _reference fields consistently

.github/workflows/pr.yml
That path doesn't look right to me. Though it looks like the checker was just falling back to checking all files before, so I guess it was doing its job despite the typo.
=> Fix typo in github actions workflow

.github/workflows/pr.yml, proto/substrait/expression.proto, proto/substrait/relations.proto
I don't think the proto-format-check a.k.a. "Check Protobuf Style" CI task was doing anything, because jidicula/clang-format-action@v4.3.1 does [not](https://github.com/jidicula/clang-format-action/blob/v4.3.1/README.md?plain=1#L36-L52) check .proto files [yet](https://github.com/jidicula/clang-format-action/blob/v4.5.0/README.md?plain=1#L59-L60), and thus it simply wasn't matching any files. If I'm right CI should fail for the first commit here, since clang-format complains about lots of things for me locally.
=> ci: proto-format-check CI job not working

proto/substrait/algebra.proto, site/docs/expressions/subqueries.md
This PR adds support for correlated subqueries to substrait.
Notes:
1. It'll be easier to review commit by commit, since I had to combine
expressions and relations together to get the protos to compile.
2. While there are actually only three kinds of subqueries (scalar, `EXISTS` and `ANY`),
we chose to keep a few of the higher level representations so that information about
the original intention is preserved.
Closes #119.
cc @pdet @Mytherin, would love your thoughts here!
=> feat: add subquery representation

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
This was added based on the discussion here: https://github.com/substrait-io/substrait/pull/102#discussion_r764248417
=> Added a section explaining how slicing reads are handled

extensions/functions_arithmetic_decimal.yaml
From [Jacques' reference](https://github.com/apache/arrow/blob/master/java/gandiva/src/main/java/org/apache/arrow/gandiva/evaluator/DecimalTypeUtil.java) we first calculate the desired precision and scale if it were unlimited (`init_prec`, `init_scale`)
If our desired precision ends up being greater than 38 then we adjust according to this logic:
```
private static final int MAX_PRECISION = 38;
private static final int MIN_ADJUSTED_SCALE = 6;
private static Decimal adjustScaleIfNeeded(int precision, int scale) {
if (precision > MAX_PRECISION) {
int minScale = Math.min(scale, MIN_ADJUSTED_SCALE);
int delta = precision - MAX_PRECISION;
precision = MAX_PRECISION;
scale = Math.max(scale - delta, minScale);
}
return new Decimal(precision, scale, 128);
}
```
So basically, if our operation might …
=> Fix typo in the decimal type derivation rules

extensions/functions_aggregate_generic.yaml, extensions/functions_boolean.yaml, extensions/functions_cast.yaml, extensions/functions_comparison.yaml, extensions/functions_datetime.yaml, extensions/functions_string.yaml
This was extracted from #120 and supersedes #147.
=> Fix incorrect function output types and add other common functions.

.github/workflows/pr.yml, proto/substrait/algebra.proto, proto/substrait/capabilities.proto, proto/substrait/extensions/extensions.proto, proto/substrait/function.proto, proto/substrait/parameterized_types.proto, proto/substrait/plan.proto, proto/substrait/type.proto, proto/substrait/type_expressions.proto
This PR reformats protos using `buf format` and adds a CI check for it as well.
=> style: format protos using buf format

site/docs/relations/logical_relations.md
Closes #158 
This clarifies that the direct schema of a read relation should report the schema before projection (i.e. it will include fields that are removed by the projection)
=> Added a slight clarification to logical_relations.md

site/requirements.txt
previously mkdocs-protobuf had pinned mkdocs. This patch updates the
mkdocs-protobuf plugin so that mkdocs is no longer pinned and removes
the workaround from #153
=> Update mkdocs-protobuf plugin

proto/substrait/algebra.proto
The expression to be matched against the literals in the ifs of a switch expression is currently missing, making it impossible to use switch expressions.
This is also in #155, but since there seems to be a push to work towards a release and I don't see the validator being merged anytime soon, I figured I'd fast-track it.
=> fix: add missing switch expression

site/docs/expressions/scalar_functions.md
See Substrait Slack channel: https://substrait.slack.com/archives/C02D7CTQXHD/p1649262963394639?thread_ts=1648724393.597809&cid=C02D7CTQXHD
=> docs(spec): remove outdated references to parameter bounds

proto/substrait/algebra.proto
While updating the type system documentation, I realized that `interval_day` literals don't currently support the advertised microsecond precision. I added support via a third microseconds component in order to be completely backward-compatible.
=> Support fractional seconds for interval_day literals

proto/substrait/algebra.proto
One of the things I noticed while writing the validator is that it is currently impossible to specify literals for user-defined types, or to specify the type variation of a literal (except for null literals, technically...). This simply adds the fields needed to do so.
=> Literals for extension types

extensions/functions_aggregate_approx.yaml
Adds a new yaml file for approximate function implementations, starting with defining `APPROX_COUNT_DISTINCT` which can be found in many databases:
[SQL Server/Azure](https://docs.microsoft.com/en-us/sql/t-sql/functions/approx-count-distinct-transact-sql?view=sql-server-ver15)
[Oracle](https://docs.oracle.com/database/121/SQLRF/functions013.htm#SQLRF56900)
[Snowflake](https://docs.snowflake.com/en/sql-reference/functions/approx_count_distinct.html)
[Spark](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.functions.approx_count_distinct.html)
[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions)
[Databricks](https://docs.databricks.com/sql/language-manual/functions/approx_count_distinct.html) …
=> Define APPROX_COUNT_DISTINCT in yaml file for approximate aggregate functions

proto/substrait/algebra.proto
Unless I'm misunderstanding something, it seems like it's currently impossible to call functions that take type arguments, such as the one from `functions_cast.yaml`:
```yaml
name: cast
description: Cast one type to another.
impls:
- args:
- value: any1
- type: output
return: output
```
since there is no way to pass type literals (copypasting the relevant bits of `algebra.proto`):
```proto
message ScalarFunction {
// points to a function_anchor defined in this plan
uint32 function_reference = 1;
repeated Expression args = 2;
Type output_type = 3;
}
message Expression {
oneof rex_type {
Literal literal = 1;
FieldReference selection = 2;
ScalarFunction scalar_function = 3;
WindowFunction window_function = 5;
IfThen if_then = 6;
SwitchExpression switch_expression = 7;
SingularOrList …
```
=> Add support for alternative argument type support in the protobuf representation (type and option arguments)

CHANGELOG.md
See https://github.com/substrait-io/substrait/pull/161#issuecomment-1134268944, looks like conventional commits doesn't pick up on the auto-generated merge commit syntax (or something?)
=> Add missing feature to 0.3.0 release notes

proto/substrait/parameterized_types.proto, proto/substrait/type.proto, proto/substrait/type_expressions.proto
As mentioned on slack (and encountered in the validator, though I'd forgotten about it apparently), it's currently impossible to specify nullability for user-defined types. It was also impossible to specify variations, which *I* see no reason to disallow, but there was no conclusion about that yet. If we do think that should be illegal, I'll also update the type docs in this PR to mention this (and why).
=> feat: support nullable and non-default variation user-defined types

site/docs/spec/specification.md
Minor fix to the links to point to the right sections.
I kept the existing [redirect map](https://github.com/substrait-io/substrait/blob/fdf7c19b58c60a13157983e00c5964625206b077/site/mkdocs.yml#L49) since I am not sure whether it is in use somewhere. 
If it's not used I think it would be better to avoid the redirect map and point directly to the right subsection.   
For example, we could use directly `types/type_classes/#compound-types` instead of `/types/compound_logical_types#compound-types`
Note that the redirect plugin doesn't support redirecting to a specific subsection (see [here](https://github.com/mkdocs/mkdocs-redirects/issues/16))
=> docs: fix spec components links

site/docs/serialization/binary_serialization.md
The link was broken when the protobuf definition were moved under `proto/substrait`
=> docs: fix broken link

extensions/functions_arithmetic.yaml
When working on https://github.com/apache/arrow/pull/13285 we noticed that there is no overflow behavior for division.  My first thought was that overflow is not possible on division but it turns out that there is one special case of overflow when the data type is signed integers.
For example, consider 8 bit signed integers.  The range is -128,127.  However, `-128 / -1 => 128` which is outside the range.  I'm not entirely sure what `SATURATE` would mean in this case but it seems it could mean 127 for the simplicity of having one set of overflow handling options for all the arithmetic.
=> fix: add overflow behavior to integer division

extensions/functions_arithmetic.yaml
This PR adds definitions for common trigonometry functions.
=> feat: add trigonometry functions

proto/substrait/algebra.proto, site/docs/expressions/aggregate_functions.md
BREAKING CHANGE: function argument bindings were open to interpretation before, and were often produced incorrectly; therefore, this change semantically shifts some responsibilities from the consumers to the producers.
=> fix: specify how function arguments are to be bound

extensions/functions_arithmetic.yaml
The overflow behavior for `abs` is annoying but probably necessary (unless we want to aggressively upcast).
Following Arrow's lead on return types for `sign`
=> feat(arithmetic): add abs and sign to scalar function extensions

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
In collaboration with Jesus Camacho Rodriguez
=> feat: add support for DDL and INSERT/DELETE/UPDATE operations

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
This is a simple implementation for the ReferenceRel, based on conversation with @jacques-n. The key idea is that a simple positional pointer to the `repeated Rel relations` in `Plan`. This is minimal and sufficient to support DAGs and Spool, and combined with #128 this supports multi-outout without redundant execution.
=> Implementation for ReferenceRel

extensions/functions_set.yaml
Adds `is_in` and `index_in` functions to determine whether a value is a
member of a given set of values, and the index of that value if it
exists, respectively.
I put these in a new yaml file to start with, but I think we could
_probably_ stick them in `comparisons`?  Open to thoughts on where these
belong.  If we are planning to add other `set` operations (union,
difference, intersection, etc) then we may be better served by having a
separate file.
=> feat(set): add basic set membership operations

extensions/functions_comparison.yaml
=> feat: add between function

extensions/functions_string.yaml
PR to add definitions for string transform functions.
=> feat: add string transform functions

extensions/functions_logarithmic.yaml
This PR adds the log1p function.
=> feat: add log1p function

extensions/functions_string.yaml
PR to add center function.
Originally worked on in https://github.com/substrait-io/substrait/pull/248.
Instead of allowing a string with multiple characters to be used as padding, like lpad and rpad, center will only allow a single character for padding.
=> feat: add center function

extensions/functions_comparison.yaml
This PR adds the option to control whether calling `is_null` and `is_not_null` on a `nan` value returns true/false, and also adds the option to control is calling `is_nan` on a null value returns true/false/null.
=> feat: clarify behavior of is_null, is_not_null, is_nan, is_finite, and is_infinite for nulls

extensions/functions_arithmetic.yaml, extensions/functions_arithmetic_decimal.yaml
This PR ensures all options arguments are named in the arithmetic function yaml files.
=> docs: add names to arguments for arithmetic functions

extensions/functions_arithmetic.yaml
Adds a scalar function definition for `factorial(n)`
I've opted to only support `i32` and `i64`.
=> feat: add factorial scalar function

extensions/functions_comparison.yaml
=> feat: add coalesce function

extensions/functions_string.yaml
PR to regexp_replace function.
Addressed some of the comments made by @jvanstraten here: https://github.com/substrait-io/substrait/pull/256
Regular expression `modifiers` are made options here.  If there's a better way, i'm open to suggestions.
Once we can come to an agreement on how to handle this regex function, i'll submit another PR to add a few of the others.
=> feat: add regexp_replace function

extensions/functions_string.yaml
This PR includes the addition of `string_agg` operator to concatenate string column data with a separator.
=> feat: add string_agg aggregate function

extensions/functions_arithmetic.yaml
This PR includes yaml configs for `median`, `approx_median` and `count_distinct` for aggregate functions.
=> feat: add median and count_distinct aggregation functions

extensions/functions_arithmetic.yaml
The behavior of count_distinct can already be accomplished with the regular count function using the distinct input property on the binding.
=> fix: revert addition of count_distinct aggregate function

extensions/functions_arithmetic.yaml, extensions/functions_boolean.yaml
Adding the `bool_and` and `bool_or` aggregation functions.
=> feat: add bool_and and bool_or aggregate functions

extensions/functions_arithmetic.yaml
This PR includes a minor fix on the missing argument names in the `functions_arithmetic.yaml`
=> fix: add missing arg names in arithmetic functions

extensions/functions_boolean.yaml
This PR adds missing arg names in the `functions_boolean.yaml`. I also replaced the name `x` to `a` to keep the naming consistency in the file. I have missed this when making the previous PR on `bool_or` and `bool_and`.
=> fix(naming): add/replace arg names in functions_boolean.yaml

extensions/functions_datetime.yaml
This PR adds the missing arg names in `functions_datetime.yaml`.
=> fix(naming): add missing arg names in functions_datetime.yaml

extensions/functions_aggregate_approx.yaml, extensions/functions_aggregate_generic.yaml
This PR adds the missing argument names in `functions_aggregate_approx.yaml` and `functions_aggregate_generic.yaml`.
=> fix(naming): add missing arg names in functions_aggregate_*.yaml

extensions/functions_arithmetic.yaml, extensions/functions_logarithmic.yaml
This PR adds options which allow specification of behaviour when dividing by 0 or when trying to calculate log of 0.  See discussion on https://github.com/substrait-io/substrait/pull/302 for more detail.
=> feat: add options for behaviour when dividing by zero or calculating log zero

extensions/functions_arithmetic.yaml
This PR clarifies the correlation measure.  I half wondered if this should be an option (i.e. Pearson's/Kendall/Spearman) but Postgres seems to use the Pearson Correlation Coefficient, but I concluded that adding in the possible choice might be a bit niche for what we're trying to do here.
=> docs: clarify correlation measure

site/docs/relations/logical_relations.md
I assume that this should not be specific but generic.
=> docs: remove outdated TBD and reference to iceberg in filter description of read relation

site/docs/types/type_classes.md, text/simple_extensions_schema.yaml
This implements and documents the things discussed in https://substrait.slack.com/archives/C02D7CTQXHD/p1662542471566549.
=> feat: support non-struct type class structure

extensions/functions_string.yaml
PR adds functions for splitting strings and fixed some spacing in the options of other functions.
=> feat: add functions for splitting strings

proto/substrait/plan.proto
BREAKING CHANGE: renamed `Version.{major -> major_number, minor -> minor_number}`
BREAKING CHANGE: renamed `Version.{patch -> patch_number}` for consistency
=> fix: Rename Version fields which conflict with <sys/sysmacros.h>

extensions/functions_aggregate_approx.yaml, extensions/functions_aggregate_generic.yaml, extensions/functions_arithmetic.yaml, extensions/functions_arithmetic_decimal.yaml, extensions/functions_boolean.yaml, extensions/functions_datetime.yaml, extensions/functions_logarithmic.yaml, extensions/functions_set.yaml, extensions/functions_string.yaml, extensions/type_variations.yaml, proto/substrait/algebra.proto, site/docs/expressions/scalar_functions.md, site/docs/extensions/generate_function_docs.py, site/docs/extensions/index.md, text/simple_extensions_schema.yaml
BREAKING CHANGE: optional arguments may now be omitted.  However, if they are specified then they MUST be named.
=> feat: add names to args at invocation and allow omitting optional args

.commitlintrc.js
This adds a workaround (until fixed upstream) for dependabot commit messages:
```
⧗   input: chore(deps): bump mkdocs-markdownextradata-plugin in /site
Bumps [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin) from 0.2.4 to 0.2.5.
- [Release notes](https://github.com/rosscdh/mkdocs-markdownextradata-plugin/releases)
- [Commits](https://github.com/rosscdh/mkdocs-markdownextradata-plugin/compare/0.2.4...0.2.5)
✖   body's lines must not be longer than 100 characters [body-max-line-length]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```
=> chore: commitlint workaround for dependabot body-max-line-length problems

proto/substrait/algebra.proto, site/docs/expressions/specialized_record_expressions.md
It's currently impossible to formulate expressions like `(field 0 - field 1, field 0 + field 1)` (using `(x, y)` as a two-field struct):
- struct literals don't work because the fields aren't literals;
- mask expressions don't work because the fields aren't pure field references;
- extension functions don't work in general unless one is made specifically for structs with the desired number of fields, the desired nullability, and the desired type variation.
The same applies for lists and maps, though if we ignore type variations, the same could hypothetically be done for them with a finite number of function extensions in core.
This construct effectively makes struct/list/map literals and (I think) mask expressions redundant, but I didn't deprecate them because they at least feel …
=> feat: add nested type constructor expressions

text/simple_extensions_schema.yaml
This adds a `Simple Extensions` title to the simple extensions schema file. I'm generating some code to read simple extensions, and it helps to have a title here (for the name for the top-level type).
=> feat: add title to simple extensions schema

site/docs/relations/logical_relations.md
This fixes a typo in the logical relations doc.
=> docs: fix a typo in logical relations doc

site/data/committers.yaml, site/data/smc.yaml, site/docs/_config, site/docs/governance.md, site/mkdocs.yml, site/requirements.txt
Copies and converts the approved governance doc to markdown, I added some links and added a plugin that generates a table based on two yaml files with the project roster.
=> docs: add governance doc to site

extensions/functions_string.yaml
BREAKING CHANGE: renamed function `regex_string_split` to `regexp_string_split` for consistency
=> fix: rename regex_string_split to regexp_string_split

site/docs/tutorial/expression_trees.svg, site/docs/tutorial/field_indices_layout.svg, site/docs/tutorial/final_plan.json, site/docs/tutorial/plan_tree_versus_expression.svg, site/docs/tutorial/sql_to_substrait.md, site/docs/tutorial/substrait_components.svg
The goal of the tutorial is to get someone to the point where they can read a serialized Substrait plan. SQL is used as a comparison since I assume most readers will have basic familiarity. JSON is used as the output format since it's used in some consumers as the input format for test.
=> docs: add tutorial for reading plans

.github/workflows/pr.yml, .github/workflows/release.yml
Version 16 is out of active maintenance as of 2 months ago.  More importantly,
version 18 is required by commitlint and our CI checks are failing without it.
=> chore: update node version in ci to 18

proto/substrait/extended_expression.proto, site/docs/expressions/extended_expression.md
This PR proposes a way for using substrait as expression only representation
and will be use for expression evaluation in big data frameworks.
=> feat: add extend expression message for expression only evaluation

site/docs/community/powered_by.md
The datafusion-substrait code recently moved into the main datafusion repo.
This updates the "Powered By" page accordingly.
=> docs: update DataFusion entry in Powered By page

extensions/functions_rounding.yaml
This PR adds `round` function.
=> feat: add round function

.github/workflows/pr.yml, .github/workflows/release.yml
The buf action in our CI scripts will, without configuration, make
anonymous calls to download artifacts from github (previous /
golden versions of the proto files that it will compare against). 
These calls may fail due to rate limiting.
By passing in the runner's github token (the one that is automatically
created).  We can bypass the strict anonymous rate limits.
=> chore: add gha token to buf to avoid rate limit failures in ci

extensions/functions_string.yaml
Quick fix for one of the string scalar functions.
=> fix(extension): fix typo in scalar function argument type

extensions/functions_datetime.yaml
BREAKING CHANGE: change return type of temporal `add` and adds `add/subtract` with `timezone`.
=> fix: change temporal add and subtract

extensions/functions_datetime.yaml
This adds new scalar functions to work with timestamp/date/time types.
See #222 for previous discussion.
=> feat: add temporal functions

.github/workflows/release.yml
The `release` job should only run on the main repository and skip on forked
repositories.
=> chore(ci): skip `release` job on forked repositories

text/simple_extensions_schema.yaml
While working on generating deserialization code based on the simple extensions
schema in https://github.com/substrait-io/substrait-rs/pull/27 I got a failing
test on extension_types.yaml.
It seems that the generated deserialization code tripped over the schema for
`structure` in items in the `types` array.
Maybe I'm misunderstanding something about the schema here, but I think we can
directly use `$ref: "#/$defs/type"` for `structure` here.
According to
https://json-schema.org/understanding-json-schema/reference/object.html#id5:
> The `additionalProperties` keyword is used to control the handling of extra
> stuff, that is, properties whose names are not listed in the `properties`
> keyword or match any of the regular expressions in the `patternProperties`
> keyword. By default any …
=> fix: remove duplication in simple extensions schema

extensions/functions_string.yaml
BREAKING CHANGE: `group` argument added to `regexp_match_substring` function
Add regexp_match_substring_all function
Resolves https://github.com/substrait-io/substrait/issues/466
=> feat: add regexp_match_substring_all function to yaml

.github/workflows/pr_title.yml
As mentioned on slack by @vibhatha the link in the conventional commits check
message did not point to the spec. This PR fixes that.
=> fix(ci): fix link to conventional commits spec

extensions/functions_arithmetic.yaml
This PR includes a resolution to https://github.com/substrait-io/substrait/issues/259
=> feat: adding SUM0 definition for aggregate functions

extensions/functions_datetime.yaml
Fix spec violation described in https://github.com/substrait-io/substrait/issues/487 by
separating `strptime` into `strptime_timestamp`, `strptime_date`, and `strptime_time`
Here's the original PR adding this in case anyone wants to see the discussion
surrounding this addition: https://github.com/substrait-io/substrait/pull/272
=> fix: separate strptime to fix spec violation

site/docs/tutorial/final_plan.json, site/docs/tutorial/sql_to_substrait.md
I noticed that the tutorial has `functions_string.yaml` and `functions_set.yaml`
mixed up for the `index_in` extension function. This PR fixes that.
=> fix: referenced simple extension in tutorial (set instead of string)

text/simple_extensions_schema.yaml
The spec on simple extensions
[states](https://substrait.io/extensions/#simple-extensions):
```
In the places where these entities are referenced, they will be referenced using a URI + name
reference.
```
And for type:
```
Type  | The name as defined on the type object.
```
However this `name` field is not marked as required on the type object
definition in the schema. This PR marks this field as required to make sure it
can always be referenced.
=> fix(text)!: mark `name` property of `type` extension item as required

extensions/functions_arithmetic.yaml
This PR add supports for timestamp types in max/min function.
This is currently supported in Acero and I believe most databases support this as well.
=> feat: add timestamp in max/min function

extensions/functions_string.yaml
When only two arguments are specified then the method will return everything
from `start` to the end of the string.  This variant is implemented in pretty much
all major engines today.
=> feat: add a two-arg variant of substring

proto/substrait/algebra.proto
The `ExchangeRel` is already in the spec, but it is not a type of `Rel` yet.
=> feat: add ExchangeRel as a type in Rel

extensions/functions_string.yaml
The substring function `start` parameter has different behavior between different 
backends when it's value negative.  Sqlite will wrap around the end of the input string,
whereas postgres will start from the left of the input string.
=> feat: add options to substring for start parameter being negative

proto/substrait/algebra.proto, site/docs/relations/physical_relations.md
Adds an expand relation.  This relation can be used to create near-duplicate
copies of each input row based on templates describing how to create the
copies.  This is used within spark to implement certain operations like aggregate
rollup and pivot longer.
=> feat: add expand rel

.pre-commit-config.yaml, tools/proto_prefix.py
* use flake8 from github
* update pre-commit hooks
=> ci: pre-commit updates

site/docs/extensions/index.md, site/docs/serialization/binary_serialization.md
#537 clarified that compound extension signatures are now required.
I noticed that the table specifying how to type those signatures didn't 
include booleans -- I _think_ it's probably `bool` but either way it 
should be included.
Also in this PR, a quick indentation fix so that the `Note:` admonitions
render correctly (there needs to be blank line and then an indented block)
=> docs: clarify compound extension signature naming for bools

extensions/functions_arithmetic.yaml
PR to add more window functions:
* first_value
* last_value
* nth_value
* lead
* lag
=> feat: add more window functions

site/docs/types/type_classes.md
Closes #447 
BREAKING CHANGE: The minimum precision for floating point numbers is
now mandated.
=> feat: explicitly reference IEEE 754 and mandate precision as well as range

extensions/extension_types.yaml, extensions/functions_geometry.yaml, site/docs/extensions/generate_function_docs.py
PR to add new geometric data types and functions.
=> feat: add geometric data types and functions

extensions/functions_comparison.yaml
BREAKING CHANGE: nullability of is_not_distinct_from has changed
=> fix!: specify nullability for is_not_distinct_from

CHANGELOG.md, site/docs/_config, site/docs/about.md, site/docs/community/index.md, site/docs/index.md
Moves the design principles behind Substrait into a separate "About Substrait"
page to allow the homepage to focus on the task of explaining what Substrait is.
=> docs:  focus homepage on discussing what Substrait is

extensions/functions_geometry.yaml
PR to geometry accessor geospatial functions
=> feat: initial commit for adding geometry accessor functions

extensions/functions_geometry.yaml
PR to add geometry editor functions
=> feat: add geometry editor functions

extensions/functions_geometry.yaml
PR to add geometry processing functions
=> feat: geometry processing functions

proto/substrait/algebra.proto
This PR adds the NestedLoopJoinRel proto definition.
Closes https://github.com/substrait-io/substrait/issues/456
=> feat: add NestedLoopJoinRel definition

extensions/functions_comparison.yaml
PR to add functions for `least` and `greatest`.
=> feat: add least and greatest functions to functions_comparison.yml

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
The `ReferenceRel`, `WriteRel`, and `DdlRel` were defined in `algebra.proto` but not part
of `message Rel` which meant they were unusable.  This PR adds those back.  It is
inspired by #288 but more targeted in scope.  One change from that original PR which I
also kept was replacing the word `tuple` with `record` in the documentation for consistency.
This is not to imply that `ReferenceRel`, `WriteRel`, or `DdlRel` are "complete" or "stable"
in any way.  I feel these relations are still quite ill defined.  However, my hope is that by
making them usable we can inspire further change to them.
BREAKING CHANGE: The enum `WriteRel::OutputMode` had an option change from
`OUTPUT_MODE_MODIFIED_TUPLES` to `OUTPUT_MODE_MODIFIED_RECORDS`
BREAKING CHANGE: The message `AggregateFunction.ReferenceRel` …
=> feat: add missing rels to rel message

extensions/functions_arithmetic.yaml
BREAKING CHANGE: Renamed modulus to modulo. 
Added options and documentation for the modulo operator as defined in math and comp sci.
Refs: #353
=> fix: renamed modulus to modulo; updated modulo operator defintion

proto/substrait/algebra.proto
This PR (hopefully) concludes various discussions around flags such as `null_equals_null`
(Datafusion) and `null_aware` (Velox).  The goal of these flags is to slightly tweak the
definition of "equality" in an equijoin relation.
This PR introduces a new EquiJoinKey message that can be used by physical join relations
to define how keys should be compared.
These custom equality functions are needed in a variety of scenarios:
Set operations (e.g. set difference) can sometimes be satisfied by an equi-join.  When this
happens the user typically wants the equality comparison to be "is not distinct from"
Some kinds of correlated subqueries can be removed during optimization and replaced with
an anti-join.  Depending on the original query ("not in" vs "where not exists") there may be
slightly …
=> feat: add custom equality behavior to the hash/merge join

.github/workflows/pr.yml, .github/workflows/pr_title.yml, .github/workflows/release.yml
It seems node 18 is now in maintenance mode and
some tools are dropping support for it
=> chore: bump node version from 18 to 20 in CI scripts

.github/workflows/pr_title.yml
The PR title check makes sure that the eventual commit message that
Github generates follows our commit message rules.  To do this we
have to emulate the way that Github creates commit messages (by
combining the PR title with the description).
In practice, Github also applies appropriate line-wrapping to ensure
that no line in the commit message is too long.  Unfortunately, our
emulation doesn't do this.  As a result, we have to write strangely
truncated descriptions in Github and this is mildly annoying.
Instead, we can just disable these rules.  They are enforced by
Github anyways when the commit message is created and so it
isn't really possible to break them (unless you use a single word with
more than 80 characters but hopefully a reviewer will notice that).
=> chore: remove unnecessary commit title checks

extensions/functions_datetime.yaml
Add multiplication of an interval by an integral number `multiply_interval(x,y)`
+ x can be i8, i16, i32 or i64
+ y can be interval_day or interval_year
=> feat: add interval multiplication

extensions/functions_comparison.yaml, extensions/functions_string.yaml
There were some instances of `BOOLEAN` and some instances of `boolean`.  All other human readable type names in the YAML are using lowercase (except when we use templated names like `T`).  The docs state that we prefer lowercase:
https://github.com/substrait-io/substrait/blob/3251b1fc5ede5788502be989b8eab778051d7a4d/site/docs/types/type_parsing.md?plain=1#L13
=> refactor: prefer boolean over BOOLEAN

extensions/functions_string.yaml
This PR adds an `null_handling ` option to the concat function.
Some engines have two versions of the concat function.  Where one ignores null arguments.
example:
Postgres has the `||` operator which doesn't ignore nulls and `concat` which does ignore nulls 
https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-concat-function/
=> feat: add ignore nulls options to concat function

extensions/functions_logarithmic.yaml
BREAKING CHANGE:  Adding a NULL option to the on_domain_errors.
SQLite returns null for some inputs such as negative infinity
=> feat: add extra option for on domain errors in log functions

extensions/functions_arithmetic_decimal.yaml
This PR adds support for decimal types in the sum0 function.
This is currently supported in Calcite.
=> feat: add decimal type support for sum0 function

ci/release/dry_run.sh, ci/release/prepare.sh, ci/release/publish.sh, ci/release/run.sh, ci/release/verify.sh
It appears our CI tool for checking license headers recently added support for .sh files: https://github.com/enarx/spdx/commit/55e0a1ae572fb42599078d1eb00c334fee3adece
This was causing failures like: https://github.com/substrait-io/substrait/actions/runs/8647423006/job/23708835580?pr=615
=> chore: add license header to shell files

extensions/functions_arithmetic.yaml
The division functions do not allow you to specify `on_domain_error` or `on_division_by_zero` for integer division operations.  However, some engines return an error in this case and some return null.
In addition, when dealing with floating point operations, some engines return null, some return an error, and some return nan.  The option to return null was missing.  This PR adds that.
=> feat: expand division function options

extensions/functions_arithmetic.yaml
This PR removes some implicit casts that exist in the trig functions.
More discussion here:
https://github.com/substrait-io/substrait/issues/251
Most of the trig functions already follow this behavior. This should handle the remaining ones.
=> fix: remove implicit casts in trig extension functions

extensions/functions_arithmetic.yaml, extensions/functions_logarithmic.yaml
This PR adds `i64` as an argument to `exp`, `ln`, `log10`, `log2` and `logb` functions
=> feat: add i64 variant for exp, ln, log10, log2 and logb functions

extensions/functions_set.yaml
`index_in` is currently declared as returning an `int64`,
the return type should be `i64`, as according to
https://substrait.io/types/type_classes/#simple-types 
there is no int64 type.
=> fix: index_in has wrong return type

extensions/functions_arithmetic.yaml
Addresses a duplication of `min` and `max` function overloads
for timestamp types.
The functions are declared in `arithmetic` extensions: 
* `min` -> https://github.com/amol-/substrait/blob/main/extensions/functions_arithmetic.yaml#L1217-L1230
* `max` -> https://github.com/amol-/substrait/blob/main/extensions/functions_arithmetic.yaml#L1217-L1230
but are also declared in `datetime` extensions:
* `min` -> https://github.com/amol-/substrait/blob/main/extensions/functions_datetime.yaml#L807-L820
* `max` -> https://github.com/amol-/substrait/blob/main/extensions/functions_datetime.yaml#L852-L865
This seems to be a source of confusion for a system loading those extensions definition, which one of the two should be considered valid?
The PR addresses this by preserving only the definitions in …
=> fix: duplicate declaration of min:timestamp & max:timestamp

site/docs/expressions/scalar_functions.md
As mentioned in #639. 
Fix the property name `Type` to `Value` for value argument.
And add missing property `description` for all argument types.
cc @westonpace 
The rendered html changes as following:
| Old    | New |
| -------- | ------- |
| <img width="954" alt="Screenshot 2024-05-16 at 10 19 11 PM" src="https://github.com/substrait-io/substrait/assets/169244206/cb55ae79-d4d3-4efb-9f3b-88063baa20d8"> | <img width="954" alt="Screenshot 2024-05-16 at 10 15 35 PM" src="https://github.com/substrait-io/substrait/assets/169244206/f0c66537-7b5b-4bd6-a34b-ceb4589b8abc"> |
| <img width="859" alt="Screenshot 2024-05-16 at 10 20 27 PM" src="https://github.com/substrait-io/substrait/assets/169244206/14e3f3af-b65a-49f7-9acb-4ac9c4ccead9"> | <img width="870" alt="Screenshot 2024-05-16 at 10 20 …
=> docs: fix properties of argument types in scalar_functions.md

extensions/functions_arithmetic_decimal.yaml
=> feat: abs add decimal type

text/simple_extensions_schema.yaml
This came up in a [discussion on a substrait-rs PR](https://github.com/substrait-io/substrait-rs/pull/185#discussion_r1603513149): it doesn't make sense for the options field of enum args to be empty. This PR modifies the schema to state that the `options` array of enum args should be non-empty.
I recommend reviewers to take a look at the first commit to see what this PR changes, the second commit is applying auto-formatting and moving the variants of `oneOf` to reference other definitions, and adding a def for `enum_options`.
~~This is a breaking change, because extensions with empty options array are no longer considered valid.~~
=> fix: specify a minimum length for the options of enum args

ci/release/dry_run.sh, ci/release/run.sh
This fixes the release scripts.
=> fix(ci): pin `conventional-changelog-conventionalcommits` to `7.0.2`

ci/release/dry_run.sh, ci/release/run.sh
Resolves #655
If we pin both `semantic-release` and  `conventionalcommits` it should stop the random breakages when one of them pushes a new release.
Updated in both the `dry_run.sh` and `run.sh` scripts.
=> chore(ci): pin semantic release

extensions/functions_string.yaml
Initcap is like "[title](https://github.com/Blizzara/substrait/blob/70d1eb71623ca0754157dd5d87348bae51d420c4/extensions/functions_string.yaml#L1023)", but while "title" defines articles
are not to be capitalized, initcap capitalizes also articles.
Initcap is supported by basically all DB systems, including Spark and DataFusion
=> feat: add "initcap" function

proto/substrait/algebra.proto
Same goal as in #648 - to support what Spark's and DataFusion's SubqueryAlias relation does. 
As Substrait mostly only referes to columns by their index, there is no inherent need for table name/qualifiers within Substrait. However, some consumers, e.g. DataFusion, require column names to be either unique or qualified for joins, which is troublesome w/o the possibility to qualify relations.
Also, for debugging failed plans and for roundtrip testing of X -> Substrait -> X conversions, it would be convenient to have proper, human-readable names to refer to.
Closes #571
=> feat: allow naming/aliasing relations

extensions/functions_aggregate_generic.yaml
This adds a "ignore_nulls" option for `any_value` that can be used when converting e.g. Spark's first()/first_value()/any_value()
=> feat: add null input handling options for `any_value`

proto/substrait/algebra.proto, proto/substrait/type.proto
BREAKING CHANGE: changes the message type for Literal PrecisionTimestamp and PrecisionTimestampTZ
The PrecisionTimestamp and PrecisionTimestampTZ literals were introduced in #594, and there was some discussion about their contents in https://github.com/substrait-io/substrait/pull/594#discussion_r1471844566. In their current form, they only contain a i64 value, which I believe is meant to be a precision-dependent number of fractional seconds since epoch. However, the literals don't contain the precision itself, so it's impossible to interpret a PrecisionTimestamp or PrecisionTimestampTZ literal without other information. This is in contrast to e.g. varchar, whose literal does specify the length, or decimal, whose literal specifies scale and precision. @westonpace curious for your thoughts …
=> fix: include precision information in PrecisionTimestamp and PrecisionTimestampTZ literals

proto/substrait/algebra.proto
[Gluten's version](https://github.com/apache/incubator-gluten/blob/73eb21db45a83c3180518bfcef3c5d343595f452/gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto#L138) of text file support relies on a named schema which shouldn't be necessary given that by its given nature a text file is comprised of strings.  This version doesn't attempt to define a schema or ways to mangle text into that schema.
=> feat: add CSV (text) file support

core.go, go.mod
This facilitates substrait assets use in go projects
=> feat: make substrait repo a go module

extensions/functions_geometry.yaml
argument type for is_closed function is missing `u!` before geometry udt causing a parser to treat it as a non-existent builtin data type.
=> fix: add missing udt identifier in functions_geometry

site/docs/governance.md
This PR adds the concept of `-contrib` repositories to the governance rules of Substrait. To that aim, the following changes are made:
* Mention that there is a distinction between "core" and `-contrib` repositories in the introduction of the Substrait project. Those definitions are used in what follows.
* Say that contributors can be given write access to `-contrib` repositories by the SMC. This allows people to make changes to those repositories without being promoted to committers.
* Clarify that committers are people who have write access to all repositories, i.e., "core" and `-contrib` repositories. This makes clear that having write access to a `-contrib` repository doesn't make someone a committer.
* Add a voting rule for `-contrib` repositories:
* The SMC needs to vote to create …
=> docs: add definition and voting rules of `-contrib` repositories

site/docs/faq.md
These two questions come up often on Slack / other channels and I felt it was time to update the FAQ.
=> docs: add two frequently asked questions to the FAQ

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
* This enables expressing Virtual table having values as expression
* Example query: `select * from (values (1+2, 'Hello'||'World'))`
* Mark existing literal field "values" as deprecated
=> feat: enhance VirtualTable to have expression as value

proto/substrait/algebra.proto
BREAKING CHANGE: changes the message type for Expressions field in VirtualTable
Fixed issue mentioned in [this](https://github.com/substrait-io/substrait/pull/711#issuecomment-2439930751)
I have fixed it by fixing recently introduced field. Though this is a breaking change but since this field is introduced very recently so I assume this won't have many consumers. So, instead of having another field I decided to fix existing field
=> fix: virtualTable expression should represent a row of expression

.github/workflows/licence_check.yml
[8dd1a10](https://github.com/enarx/spdx/commit/8dd1a10623686920a56406bbacb795c61fa23343) changes license listing format to be separated by new lines. We should change the github action yml accordingly.
=> chore(ci): use licenses separated by new line

site/data/committers.yaml
This PR adds the committers promoted by the [vote](https://groups.google.com/g/substrait/c/abti2mcJhH8/m/wVRuSdwSAgAJ) on October 24, 2024 to the relevant document on the web site.
=> docs: add committers promoted on 10/24/2024

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
* Update FetchRel in Substrait to support expressions for both offset and count. 
This is done in a way that should be effectively compatible with old systems. Old plans should be able to continue to be consumed treating the old values as int64.
BREAKING CHANGE: The encoding of FetchRel has changed in a strictly backwards incompatible way. The change involves transitioning offset and count from a standalone int64 field to a oneof structure, where the original int64 field is marked as deprecated, and a new field of Expression type is introduced. Using a oneof may cause ambiguity between unset and set-to-zero states in older messages. However, the fields are defined such that their logical meaning remains indistinguishable, ensuring consistency across encodings.
=> feat: add expression support for count and offset in the fetch operator

site/docs/relations/basics.md, site/docs/relations/logical_relations.md
This PR fixes several usages of the word "dataset". In one occasion, the word "transformation" was used when really the *result* of such a transformation was meant, for which the spec uses the word "dataset". In two other occasions, the word "dataset" was used when really the *transformation* that produces such a dataset was meant, for which the spec uses the words "transformation", "relation", "operation", or "operator."
=> docs: fix some usages of the word "dataset"

proto/substrait/algebra.proto, site/docs/relations/logical_relations.md
Adds Iceberg table type and first sub-variety, reading manifest files directly.
=> feat: introduce Iceberg table type using metadata file

site/docs/extensions/generate_function_docs.py
This PR fixes the logic in `generate_function_docs.py` that generates the docs for the options of functions. The previous version mixed up the option names and the corresponding choices, leading to non-sensical docs such as reported in #755. This PR collects the option names and corresponding choices jointly such that no mix-up can happen. I have looked at the output that is changed by this script but only superficially so: my impression is that (1) some options now come in a different order (because the previous order was determined by the order of keys in a `dict`, which is implementation-defined) and (2) the remaining changes come from the intention of this PR, i.e., the constitute fixes of previously non-sensical output. However, since I am not intrically familiar with all extension …
=> docs: fix and simplify logic that generates extension options docs

extensions/functions_rounding_decimal.yaml, tests/cases/rounding_decimal/ceil.test, tests/cases/rounding_decimal/floor.test, tests/cases/rounding_decimal/round.test
The round function has a number of variants to support different numeric types.  This commit adds support for rounding decimals. This is required for the spark module.
=> feat: add decimal argument support to round function

text/simple_extensions_schema.yaml
Small change to add optional 'description' field to types definition in YAML schema.
=> feat: add description field to types definition in schema

extensions/functions_arithmetic.yaml, tests/cases/arithmetic/shift_left.test, tests/cases/arithmetic/shift_right.test, tests/cases/arithmetic/shift_right_unsigned.test
Proposed addition of the bitwise shift functions to the core arithmetic function yaml as supported by a number of SQL implementations. 
E.g. Spark - https://spark.apache.org/docs/latest/api/sql/index.html#shiftleft
=> feat: bitwise shift functions

site/docs/relations/logical_relations.md
Clarifies that `SELECT DISTINCT`, a common SQL operation, is implemented using aggregate relations without measures. 
This came up recently as a question I fielded, and it wasn't obvious from the docs, so it seemed like it might be useful to make it clearer.
=> docs: clarify SELECT DISTINCT

site/docs/expressions/window_functions.md
The window functions page on the site refers to binding aggregate functions instead of window functions.
=> fix: typo on window functions site page
